services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - "4005:4005"
      - "4006:4006"
    env_file:
      - .env
  postgres:
    image: postgres:latest
    restart: unless-stopped
    hostname: postdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    restart: always
    image: nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/public/:/www/data/public/
      - /etc/letsencrypt/live/slacktipbot.bradenbagby.com/:/etc/letsencrypt/live/slacktipbot.bradenbagby.com/
      - /etc/letsencrypt/archive/slacktipbot.bradenbagby.com/:/etc/letsencrypt/archive/slacktipbot.bradenbagby.com/
    ports:
      - 80:80
      - 443:443
    networks:
      - default

volumes:
  postgres_data:
  logs:
